# Generated by Django 5.2.5 on 2025-08-23 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='UserImages/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2025, 8, 23, 17, 17, 26, 877053, tzinfo=datetime.timezone.utc))),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('NA', 'OTHERS')], max_length=2)),
            ],
        ),
    ]
