# Generated by Django 5.2.5 on 2025-08-24 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='discription',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 6, 41, 28, 695424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('GAYYY', 'GAY')], max_length=5),
        ),
    ]
