# Generated by Django 5.2.5 on 2025-08-24 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_myusers_discription_alter_myusers_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=500),
        ),
        migrations.CreateModel(
            name='myUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myApp.myusers')),
            ],
        ),
    ]
